### ISSUE TITLE
Release note for v1.4.0 could not be found

### ISSUE THREAD

**Issue by kmaehashi** [scipy/docs.scipy.org#58]
Hi, unsure if this is the right place to report this, but it seems that the release notes for v1.4.0 is unavailable.
https://docs.scipy.org/doc/scipy/reference/release.1.4.0.html
which is linked from https://docs.scipy.org/doc/scipy/reference/release.html
Thanks.

**Comment by rgommers** [comment]
Thanks for the report @kmaehashi. The main scipy repo would be better for docs content/linking issues, but let's leave this issue here now.

Something is really slow right now loading https://docs.scipy.org/doc/. Half the internet seems to be broken at the moment, so not sure that that's due to our doc server or not. I'll try again later today.

**Comment by tupui** [comment]
I propose to close the issue since it is again the reference in the url path issue. If you hit this it works https://docs.scipy.org/doc/scipy/release.1.4.0.html

We have an issue open for it here: https://github.com/scipy/scipy/issues/14267 

Sorry for the inconvenience, in the meantime you can use the dev doc which works just fine: https://scipy.github.io/devdocs/index.html

**Comment by kmaehashi** [comment]
Thanks for the quick response!
I see, so currently there are two "Release notes" page (https://docs.scipy.org/doc/scipy/release.html and https://docs.scipy.org/doc/scipy/reference/release.html) and I was looking into the wrong (the latter) one.

Let me close this as this is duplicate as @tupui suggested.
