### ISSUE TITLE
The javascript to generate the "out of date docs" warning for old NumPy docs should only point to numpy.org

### ISSUE THREAD

**Issue by mattip** [scipy/docs.scipy.org#73]
Currently the ["out of date" docs warning](https://docs.scipy.org/doc/numpy-1.9.2/reference/c-api.iterator.html) on older NumPy docs shows this
> This is documentation for an old release of NumPy (version 1.9.2). Search for [this page](https://docs.scipy.org/doc/scipy/search.html?q=Array%20Iterator%20API) in the [documentation of the latest stable release](https://numpy.org/doc/stable/) (version > 1.17).

The first link points to the docs on https://docs.scipy.org, where it should only refer to the newer documentation on https://numpy.org. I think we can remove the first link entirely. The idea was that perhaps the newer documentation has the same structure, so the link can be recreated to the newer docs, but by now the structure has changed so much that will rarely succeed.

xref numpy/numpy#23156

**Comment by tupui** [comment]
Indeed. The first link is created using this

https://github.com/scipy/docs.scipy.org/blob/9e40a7a112d62b90d7195d27be54caaae273bbed/_static/versionwarning.js_t#L69

We could either remove it entirely, or as with other links in the code and use some conditional.

NumPy's doc is also using this JS or you have a copy on your side? In the long run, we might not have to support this mechanism anymore since the theme is having something for that purpose. (Provided we can update one day when they fix the build slowdown...)
